const mfiData = [
  {
    'brands': 'Emperor Oil',
    'companyName': 'Raffles Oil LFTZ Enterprise',
    'overallScore': 96.44,
    'sector': 'Edible Oils',
    'saScore': 98,
    'ivcScore': null,
    'iegScore': 88,
    'ptScore': 100,
    'brandId': 1
  },
  {
    'brands': 'Power Oil',
    'companyName': 'Raffles Oil LFTZ Enterprise',
    'overallScore': 96.44,
    'sector': 'Edible Oils',
    'saScore': 98,
    'ivcScore': null,
    'iegScore': 88,
    'ptScore': 100,
    'brandId': 2
  },
  {
    'brands': 'Classic All Purpose Flour',
    'companyName': 'Flour Mills of Nigeria Plc',
    'overallScore': 94.05,
    'sector': 'Flour',
    'saScore': 97,
    'ivcScore': null,
    'iegScore': 79,
    'ptScore': 100,
    'brandId': 3
  },
  {
    'brands': 'Golden Penny Sugar',
    'companyName': 'Flour Mills of Nigeria Plc',
    'overallScore': 94.05,
    'sector': 'Sugar',
    'saScore': 97,
    'ivcScore': null,
    'iegScore': 79,
    'ptScore': 100,
    'brandId': 4
  },
  {
    'brands': 'Golden Penny Prime Flour',
    'companyName': 'Flour Mills of Nigeria Plc',
    'overallScore': 90.72,
    'sector': 'Flour',
    'saScore': 97,
    'ivcScore': 97.67,
    'iegScore': 79,
    'ptScore': 83,
    'brandId': 5
  },
  {
    'brands': 'Confectionary Flour',
    'companyName': 'Flour Mills of Nigeria Plc',
    'overallScore': 90.72,
    'sector': 'Flour',
    'saScore': 97,
    'ivcScore': null,
    'iegScore': 79,
    'ptScore': 83,
    'brandId': 6
  },
  {
    'brands': 'Eagle Wheat Flour',
    'companyName': 'Flour Mills of Nigeria Plc',
    'overallScore': 90.72,
    'sector': 'Flour',
    'saScore': 97,
    'ivcScore': null,
    'iegScore': 79,
    'ptScore': 83,
    'brandId': 7
  },
  {
    'brands': 'Dangote Sugar',
    'companyName': 'Dangote Sugar Refinery Plc',
    'overallScore': 87.64,
    'sector': 'Sugar',
    'saScore': 100,
    'ivcScore': 100,
    'iegScore': 88,
    'ptScore': 50,
    'brandId': 8
  },
  {
    'brands': 'Superfine Flour',
    'companyName': 'Honeywell Flour Mills Plc',
    'overallScore': 84.38,
    'sector': 'Flour',
    'saScore': 86,
    'ivcScore': 86,
    'iegScore': 89,
    'ptScore': 75,
    'brandId': 9
  },
  {
    'brands': 'Mama Gold Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 80.76,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': 89,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 10
  },
  {
    'brands': 'All Purpose Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 80.76,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': 89,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 11
  },
  {
    'brands': 'Mix & Bake Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 80.76,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': 89,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 12
  },
  {
    'brands': 'Bakewell Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 80.76,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': 89,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 13
  },
  {
    'brands': 'Dangote Bread Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 80.76,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': 89,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 14
  },
  {
    'brands': 'Devon King\'s',
    'companyName': 'PZ Wilmar Food Ltd',
    'overallScore': 79.2,
    'sector': 'Edible Oils',
    'saScore': 79,
    'ivcScore': 79,
    'iegScore': 59,
    'ptScore': 100,
    'brandId': 15
  },
  {
    'brands': 'Mamador',
    'companyName': 'PZ Wilmar Food Ltd',
    'overallScore': 79.2,
    'sector': 'Edible Oils',
    'saScore': 79,
    'ivcScore': 78.33,
    'iegScore': 59,
    'ptScore': 100,
    'brandId': 16
  },
  {
    'brands': 'Diamond D\'Lite',
    'companyName': 'Dufil Prima Foods Plc',
    'overallScore': 75.64,
    'sector': 'Flour',
    'saScore': 80,
    'ivcScore': 80,
    'iegScore': 88,
    'ptScore': 50,
    'brandId': 17
  },
  {
    'brands': 'Pure Flour',
    'companyName': 'Dufil Prima Foods Plc',
    'overallScore': 75.64,
    'sector': 'Flour',
    'saScore': 80,
    'ivcScore': 80,
    'iegScore': 88,
    'ptScore': 50,
    'brandId': 18
  },
  {
    'brands': 'BUA Premium Wheat Flour',
    'companyName': 'Crown Flour Mills Ltd',
    'overallScore': 74.1,
    'sector': 'Flour',
    'saScore': 89,
    'ivcScore': null,
    'iegScore': 37,
    'ptScore': 67,
    'brandId': 19
  },
  {
    'brands': 'Grand Pure Soya Oil',
    'companyName': 'Grand Cereals Ltd',
    'overallScore': 73,
    'sector': 'Edible Oils',
    'saScore': 65,
    'ivcScore': 65,
    'iegScore': 70,
    'ptScore': 100,
    'brandId': 20
  },
  {
    'brands': 'Golden Penny Pure Soya Oil',
    'companyName': 'Premium Edible Oils Ltd',
    'overallScore': 68.02,
    'sector': 'Edible Oils',
    'saScore': 52,
    'ivcScore': 52.14,
    'iegScore': 84,
    'ptScore': 100,
    'brandId': 21
  },
  {
    'brands': 'Golden Penny Pure Vegetable Oil',
    'companyName': 'Premium Edible Oils Ltd',
    'overallScore': 68.02,
    'sector': 'Edible Oils',
    'saScore': 52,
    'ivcScore': 52.14,
    'iegScore': 84,
    'ptScore': 100,
    'brandId': 22
  },
  {
    'brands': 'Royal Bake Wheat Flour',
    'companyName': 'Dufil Prima Foods Plc',
    'overallScore': 67.31,
    'sector': 'Flour',
    'saScore': 80,
    'ivcScore': 80,
    'iegScore': 88,
    'ptScore': 8,
    'brandId': 23
  },
  {
    'brands': 'Kings Flour',
    'companyName': 'Kings Flour Mill Ltd',
    'sector': 'Flour',
    'overallScore': 65.76,
    'saScore': 64,
    'ivcScore': null,
    'iegScore': 37,
    'ptScore': 100,
    'brandId': 24
  },
  {
    'brands': 'Sunola Soya Oil',
    'companyName': 'Sunola Foods Ltd',
    'overallScore': 60.6,
    'sector': 'Edible Oils',
    'saScore': 48,
    'ivcScore': 48,
    'iegScore': 59,
    'ptScore': 100,
    'brandId': 25
  },
  {
    'brands': 'Active Premium Vegetable Oil',
    'companyName': 'Apple & Pears Ltd',
    'overallScore': 59.26,
    'sector': 'Edible Oils',
    'saScore': 53,
    'ivcScore': null,
    'iegScore': 38,
    'ptScore': 100,
    'brandId': 26
  },
  {
    'brands': 'Laziz Pure Vegetable Oil',
    'companyName': 'Apple & Pears Ltd',
    'overallScore': 59.26,
    'sector': 'Edible Oils',
    'saScore': 53,
    'ivcScore': null,
    'iegScore': 38,
    'ptScore': 100,
    'brandId': 27
  },
  {
    'brands': 'Winner Pure Soya Oil',
    'companyName': 'Apple & Pears Ltd',
    'overallScore': 59.26,
    'sector': 'Edible Oils',
    'saScore': 53,
    'ivcScore': null,
    'iegScore': 38,
    'ptScore': 100,
    'brandId': 28
  },
  {
    'brands': 'BUA Sugar',
    'companyName': 'BUA Foods Plc',
    'overallScore': 48.38,
    'sector': 'Sugar',
    'saScore': 68,
    'ivcScore': null,
    'iegScore': 38,
    'ptScore': 0,
    'brandId': 29
  },
  {
    'brands': 'Activa Pure Vegetable Oil',
    'companyName': 'Golden Oil Industries Ltd',
    'overallScore': 47.97,
    'sector': 'Edible Oils',
    'saScore': 36,
    'ivcScore': 35.63,
    'iegScore': 33,
    'ptScore': 100,
    'brandId': 30
  },
  {
    'brands': 'Sunola Sugar',
    'companyName': 'Sunola Foods Ltd',
    'overallScore': 45.6,
    'sector': 'Sugar',
    'saScore': 48,
    'ivcScore': null,
    'iegScore': 59,
    'ptScore': 25,
    'brandId': 31
  }
];

export default mfiData;
